[nfs]
172.31.26.116

[webservers]
172.31.26.226
172.31.29.104

[db]
172.31.30.29

[lb]
172.31.29.156

[deployment:children]
db
lb

[deployment:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/libexec/platform-python
